version: 2.1
orbs:
  codecov: codecov/codecov:3.0.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          run: |
            coverage run tests.py
            coverage xml
      - codecov/upload
