name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: pytest --cov app --junitxml=reportme.xml
        continue-on-error: true

      - name: Upload coverage to Codecov
        run: |
          curl -Os https://cli.codecov.io/v0.4.6/linux/codecov
          chmod u+x codecov

          ./codecov -v upload-process -f reportme.xml -t ${{ secrets.CODECOV_TOKEN }} --report-type test_results
