name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov app --junitxml=testresults.xml

      - name: cat testresults.xml
        run: cat testresults.xml

      - name: Install CLI
        run: pip install --no-cache-dir git+https://github.com/codecov/codecov-cli.git@joseph/test-results-staging
      - name: Upload test results to Codecov
        run: codecovcli -v -u ${{ secrets.CODECOV_STAGING_API_URL }} do-upload --report-type test_results --file testresults.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN_STAGING }}
      - name: Upload coverage to Codecov
        run: codecovcli -v -u ${{ secrets.CODECOV_STAGING_API_URL }} do-upload
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN_STAGING }}
